### PR TITLE
ci: add build.yml

### LINKED ISSUE #5: Add github actions to run tests

### PR DESCRIPTION
**Pull request by flaneur2020**
fixes #5

### CODE REVIEW

**Comment by flaneur2020** [comment]
it seems that the test case `TestSameOffset` failed in the workflow, i temporarily skipped it in this pr, and i suppose we can put it in another pr after the ci workflow established.

**Comment by avinassh** [comment]
@flaneur2020 I don't mind having a failing CI instead of tests disabled. Could you not skip the test? rest  of the PR it looks great

also, any idea which version of minio it uses? logging it in the CI would be very helpful in debugging

**Comment by flaneur2020** [comment]
@avinassh reverted the skip, and changed to directly use `docker run` to bootstrap the minio. (and the test passes, it seems the failure was caused by the previous minio-server server was too old) now it uses the latest minio/minio image from official docker hub

**Comment by avinassh** [comment]
awesome! That's why I was asking for minio version ;) 

Thank you for the PR. And you are the first contributor 🥳 

tenor

**Pull request merged**
